version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13391
      POSTGRES_DB: hn_job_board
    ports:
      - "5432:5432"

  api:
    image: hn-backend
    env_file:
      - backend/.env.docker
    depends_on:
      - db
    ports:
      - "8000:8000"
